-- Oracle 23c Free初期化スクリプト
-- 権限付与（systemユーザーで実行）
GRANT CONNECT, RESOURCE, DBA TO system;
GRANT CREATE SESSION TO system;
GRANT CREATE TABLE TO system;
GRANT CREATE SEQUENCE TO system;
GRANT CREATE TRIGGER TO system;
GRANT UNLIMITED TABLESPACE TO system;

-- ユーザーテーブル作成
CREATE TABLE users (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    age NUMBER(3),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- インデックス作成
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_name ON users(name);
CREATE INDEX idx_users_created_at ON users(created_at);

-- テストデータ挿入
DECLARE
    i NUMBER := 1;
BEGIN
    WHILE i <= 10000 LOOP
        INSERT INTO users (name, email, age) 
        VALUES (
            'User' || TO_CHAR(i),
            'user' || TO_CHAR(i) || '@example.com',
            20 + MOD(i, 50)
        );
        i := i + 1;
    END LOOP;
    COMMIT;
END;
/

-- パフォーマンステスト用のプロシージャ
CREATE OR REPLACE PROCEDURE GetUsersByAgeRange(
    p_min_age IN NUMBER,
    p_max_age IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT id, name, email, age, created_at, updated_at
        FROM users 
        WHERE age BETWEEN p_min_age AND p_max_age
        ORDER BY created_at DESC;
END;
/

-- バッチ挿入用のプロシージャ
CREATE OR REPLACE PROCEDURE BulkInsertUsers(
    p_user_data IN CLOB
) AS
    l_users JSON_ARRAY_T;
    l_user JSON_OBJECT_T;
    l_name VARCHAR2(255);
    l_email VARCHAR2(255);
    l_age NUMBER;
BEGIN
    l_users := JSON_ARRAY_T(p_user_data);
    
    FOR i IN 0 .. l_users.get_size - 1 LOOP
        l_user := JSON_OBJECT_T(l_users.get(i));
        l_name := l_user.get_string('name');
        l_email := l_user.get_string('email');
        l_age := l_user.get_number('age');
        
        INSERT INTO users (name, email, age) 
        VALUES (l_name, l_email, l_age);
    END LOOP;
    
    COMMIT;
END;
/

-- 更新時間自動更新トリガー
CREATE OR REPLACE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 統計情報更新
EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'USERS');

-- 完了メッセージ
BEGIN
    DBMS_OUTPUT.PUT_LINE('Oracle初期化完了');
END;
/
